### ISSUE TITLE
Primary OCR and Secondary OCR

### ISSUE THREAD

**Issue by VinayNagalgaonkar1998** [rohitsaluja22/OpenOCRCorrect#10]
How are we getting the output from Primary OCR and Secondary OCR? What are the Primary and Secondary OCR used (like Tessaract, etc.)?

**Comment by rohitsaluja22** [comment]
For Sanskrit we used Indsenz as primary OCR engine and Google Docs as secondary OCR (since tesseract was not good for Sanskrit, we haven't used it for Sanskrit.)

For other languages we used Google OCR as primary and Tesseract as secondary OCR (read the publication "Error Detection and Corrections in Indic OCR" for details.
